// Helpers to wrap a .ggb base64 blob into HTML/Markdown that students or
// instructors can paste into a webpage, GitHub Pages site, or — for Canvas —
// an iframe via the existing GeoGebra LTI integration. We do NOT try to
// reinvent the Canvas LTI flow; Canvas administrators install the GeoGebra
// LTI tool and instructors point it at materials. The embed helpers below
// are for everywhere else: a standalone HTML page, a GitHub Pages site, a
// Markdown file that allows raw HTML, etc.

export interface EmbedOptions {
  /** Width in pixels. */
  width?: number;
  /** Height in pixels. */
  height?: number;
  /** Show the GeoGebra toolbar. Default false. */
  showToolBar?: boolean;
  /** Show the algebra input bar. Default false. */
  showAlgebraInput?: boolean;
  /** Show the menu bar. Default false. */
  showMenuBar?: boolean;
  /** Show the reset icon (top-right reload button). Default true. */
  showResetIcon?: boolean;
  /** Allow shift-drag-to-zoom and panning. Default true. */
  enableShiftDragZoom?: boolean;
  /** Allow right click. Default false for student-facing embeds. */
  enableRightClick?: boolean;
  /** Disable script execution from the .ggb file. Default false (matches GeoGebra default), but the MCP-side recommendation is true. */
  enableScripting?: boolean;
  /** GeoGebra app to launch (graphing / geometry / 3d / classic / suite / cas). */
  appName?: string;
  /** A stable id for the element on the page. Default "ggb-applet". */
  elementId?: string;
  /** Optional pinned codebase, e.g. "https://www.geogebra.org/apps/5.2.846.0/web3d". */
  codebase?: string;
}

const DEFAULT_OPTS: Required<Omit<EmbedOptions, "codebase">> & { codebase?: string } = {
  width: 800,
  height: 600,
  showToolBar: false,
  showAlgebraInput: false,
  showMenuBar: false,
  showResetIcon: true,
  enableShiftDragZoom: true,
  enableRightClick: false,
  enableScripting: false,
  appName: "graphing",
  elementId: "ggb-applet",
  codebase: undefined,
};

/**
 * Build a self-contained HTML snippet that loads deployggb.js and inlines the
 * .ggb file as a base64 string. The output is one <div> + one <script> block,
 * safe to paste into a static page.
 */
export function makeEmbedHTML(ggbBase64: string, opts: EmbedOptions = {}): string {
  const o = { ...DEFAULT_OPTS, ...opts };
  const params = {
    appName: o.appName,
    width: o.width,
    height: o.height,
    showToolBar: o.showToolBar,
    showAlgebraInput: o.showAlgebraInput,
    showMenuBar: o.showMenuBar,
    showResetIcon: o.showResetIcon,
    enableShiftDragZoom: o.enableShiftDragZoom,
    enableRightClick: o.enableRightClick,
    enableScripting: o.enableScripting,
    ggbBase64: ggbBase64,
  };
  const codebaseLine = o.codebase
    ? `\n    applet.setHTML5Codebase(${JSON.stringify(o.codebase)});`
    : "";
  return `<!-- GeoGebra applet (generated by geogebra-mcp) -->
<div id="${o.elementId}"></div>
<script src="https://www.geogebra.org/apps/deployggb.js"></script>
<script>
  (function () {
    var params = ${JSON.stringify(params, null, 2).replace(/\n/g, "\n    ")};
    var applet = new GGBApplet(params, true);${codebaseLine}
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", function () { applet.inject(${JSON.stringify(o.elementId)}); });
    } else {
      applet.inject(${JSON.stringify(o.elementId)});
    }
  })();
</script>`;
}

/**
 * Markdown wrapper. Most Markdown renderers that allow raw HTML (GitHub, MkDocs,
 * Pandoc with --raw-html, Jupyter, Obsidian) render the inner block correctly.
 * Canvas's RCE allows raw HTML for instructors — this snippet works there too.
 */
export function makeEmbedMarkdown(ggbBase64: string, opts: EmbedOptions = {}): string {
  return makeEmbedHTML(ggbBase64, opts);
}

/**
 * Returns a GeoGebra Materials URL stub. If the user has uploaded the .ggb to
 * https://www.geogebra.org/materials, they can pass the material_id here to
 * embed via iframe — the recommended path for Canvas (uses the existing
 * GeoGebra LTI integration that Indiana University and most Canvas instances
 * have available).
 */
export function makeMaterialsIframe(materialId: string, opts: { width?: number; height?: number } = {}): string {
  const w = opts.width ?? 800;
  const h = opts.height ?? 600;
  const safeId = String(materialId).replace(/[^A-Za-z0-9_-]/g, "");
  return `<iframe src="https://www.geogebra.org/material/iframe/id/${safeId}/width/${w}/height/${h}" width="${w}" height="${h}" style="border:0px;" allowfullscreen></iframe>`;
}
